### ISSUE TITLE
Nvidia GPU devices in systemd will be ignored after 1.1.3

### ISSUE THREAD

**Issue by panli889** [opencontainers/runc#3671]
I found a PR https://github.com/opencontainers/runc/pull/3504/files in 1.13, in which it will ignore the devices can't be `os.Stat`. However, Nvidia GPU is that kind of device, though I do not know why.

After the version, If we use the command like this: 'docker run --device /dev/nvidia0:/dev/nvidia0', the DeviceAllow list systemd received from runc will be different from the list runc operates. So if we run `systemctl daemon-reload`, the device will not be able to access anymore.

So I'm wondering is it possible to revert the PR, or is there any other solutions?

**Comment by AkihiroSuda** [comment]
@cyphar PTAL

**Comment by panli889** [comment]
@cyphar Hi, any progress?

**Comment by kolyshkin** [comment]
@panli889 can you please check and let us know if the fix in PR #3620 also fixes your issue?

**Comment by panli889** [comment]
> @panli889 can you please check and let us know if the fix in PR #3620 also fixes your issue?

Thanks for the reply! I've test it with the code, it reports the same issue.

For the normal nvidia GPU device, the location is at `/dev/nvidia0`, and in the `common.go` now it turns to `/dev/char/195:0`. If I run it with the `os.Stat`, it still reports `no such file or directory`.

**Comment by kolyshkin** [comment]
This should be fixed in runc-1.1.7 (by PR #3845), provided systemd >= v240 is used. For older systemd versions, there's nothing we can do.

@panli889 can you please check that this fixes the issue?

**Comment by panli889** [comment]
> This should be fixed in runc-1.1.7 (by PR #3845), provided systemd >= v240 is used. For older systemd versions, there's nothing we can do.
> 
> @panli889 can you please check that this fixes the issue?

Hi @kolyshkin, Thanks for your efforts! It's ok from my vision, our systemd version is >= 240!

**Comment by zhoaxiaohu** [comment]
It seems this issue still isn't fixed，GPU permission loss
runc-1.1.7 + systemd-249 

run Container:
ctr -n k8s.io run --runc-binary /usr/bin/nvidia-container-runtime --rm --tty --env NVIDIA_VISIBLE_DEVICES=3 --env KGPU_MEM_DEV=23028 --env KGPU_SCHD_WEIGHT=0 --env KGPU_MEM_CONTAINER=10000 org.gpu.com/vgpu/video-worker-faas:1.0-release test_gpu_9 /bin/bash

```
1、guest containerd:
# crictl exec -it 4f3b9ab5871d4 /bin/bash
# nvidia-smi 
Wed Aug 20 11:30:51 2025       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:AF:00.0 Off |                  N/A |
| 22%   31C    P8    19W / 250W |      0MiB /  4785MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

2、Host:
systemctl daemon-reload 

3、guest containerd:
crictl exec -it 4f3b9ab5871d4 /bin/bash
# nvidia-smi 
Failed to initialize NVML: Unknown Error
```
