### ISSUE TITLE
criu 4.1 fail on AlmaLinux 8

### ISSUE THREAD

**Issue by kolyshkin** [opencontainers/runc#4729]
From https://cirrus-ci.com/task/5689701597708288?logs=unit_tests#L136

```
=== RUN   TestUsernsCheckpoint
time="2025-04-16T21:13:52Z" level=warning msg="--- Quoting \"/tmp/TestUsernsCheckpoint3117440493/003/criu/dump.log\""
time="2025-04-16T21:13:52Z" level=warning msg="849:(00.152996) page-xfer: Transferring pages:"
time="2025-04-16T21:13:52Z" level=warning msg="850:(00.152998) page-xfer: \tbuf 1/1"
time="2025-04-16T21:13:52Z" level=warning msg="851:(00.152999) page-xfer: \tp 0x7ffd4bea0000 [1]"
time="2025-04-16T21:13:52Z" level=warning msg="852:(00.153005) page-xfer: \th 0x7ffd4bea1000 [1]"
time="2025-04-16T21:13:52Z" level=warning msg="853:(00.153007) page-xfer: Checking 0x7ffd4bea1000/4096 hole"
time="2025-04-16T21:13:52Z" level=warning msg="854:(00.153010) Error (criu/page-xfer.c:299): page-xfer: Missing 7ffd4bea1000 in parent pagemap"
time="2025-04-16T21:13:52Z" level=warning msg="855:(00.153014) Error (criu/page-xfer.c:342): page-xfer: Hole 0x7ffd4bea1000/4096 not found in parent"
time="2025-04-16T21:13:52Z" level=warning msg="856:(00.153037) page-pipe: Killing page pipe"
time="2025-04-16T21:13:52Z" level=warning msg="857:(00.153065) ----------------------------------------"
time="2025-04-16T21:13:52Z" level=warning msg="858:(00.153067) Error (criu/mem.c:672): Can't dump page with parasite"
time="2025-04-16T21:13:52Z" level=warning msg=...
time="2025-04-16T21:13:52Z" level=warning msg="868:(00.153308) net: Unlock network"
time="2025-04-16T21:13:52Z" level=warning msg="869:(00.153312) Running network-unlock scripts"
time="2025-04-16T21:13:52Z" level=warning msg="870:(00.153314) \tRPC"
time="2025-04-16T21:13:52Z" level=warning msg="871:(00.177045) Unfreezing tasks into 1"
time="2025-04-16T21:13:52Z" level=warning msg="872:(00.177074) \tUnseizing 46190 into 1"
time="2025-04-16T21:13:52Z" level=warning msg="873:(00.177098) Error (criu/cr-dump.c:2111): Dumping FAILED."
time="2025-04-16T21:13:52Z" level=warning msg=---
    checkpoint_test.go:113: criu failed: type DUMP errno 0
--- FAIL: TestUsernsCheckpoint (0.61s)
```

**Comment by kolyshkin** [comment]
Agains (see https://cirrus-ci.com/task/5080791870341120?logs=unit_tests#L357):
```
=== RUN   TestUsernsCheckpoint
time="2025-04-17T19:01:26Z" level=warning msg="--- Quoting \"/tmp/TestUsernsCheckpoint3660773276/003/criu/dump.log\""
time="2025-04-17T19:01:26Z" level=warning msg="839:(00.166824) page-xfer: Transferring pages:"
time="2025-04-17T19:01:26Z" level=warning msg="840:(00.166826) page-xfer: \tbuf 1/1"
time="2025-04-17T19:01:26Z" level=warning msg="841:(00.166828) page-xfer: \tp 0x7ffd1d19b000 [1]"
time="2025-04-17T19:01:26Z" level=warning msg="842:(00.166847) page-xfer: \th 0x7ffd1d19c000 [1]"
time="2025-04-17T19:01:26Z" level=warning msg="843:(00.166849) page-xfer: Checking 0x7ffd1d19c000/4096 hole"
time="2025-04-17T19:01:26Z" level=warning msg="844:(00.166852) Error (criu/page-xfer.c:299): page-xfer: Missing 7ffd1d19c000 in parent pagemap"
time="2025-04-17T19:01:26Z" level=warning msg="845:(00.166855) Error (criu/page-xfer.c:342): page-xfer: Hole 0x7ffd1d19c000/4096 not found in parent"
time="2025-04-17T19:01:26Z" level=warning msg="846:(00.166876) page-pipe: Killing page pipe"
time="2025-04-17T19:01:26Z" level=warning msg="847:(00.166906) ----------------------------------------"
time="2025-04-17T19:01:26Z" level=warning msg="848:(00.166908) Error (criu/mem.c:672): Can't dump page with parasite"
time="2025-04-17T19:01:26Z" level=warning msg=...
time="2025-04-17T19:01:26Z" level=warning msg="858:(00.167217) net: Unlock network"
time="2025-04-17T19:01:26Z" level=warning msg="859:(00.167221) Running network-unlock scripts"
time="2025-04-17T19:01:26Z" level=warning msg="860:(00.167223) \tRPC"
time="2025-04-17T19:01:26Z" level=warning msg="861:(00.182697) Unfreezing tasks into 1"
time="2025-04-17T19:01:26Z" level=warning msg="862:(00.182710) \tUnseizing 47334 into 1"
time="2025-04-17T19:01:26Z" level=warning msg="863:(00.182735) Error (criu/cr-dump.c:2111): Dumping FAILED."
time="2025-04-17T19:01:26Z" level=warning msg=---
    checkpoint_test.go:113: criu failed: type DUMP errno 0
--- FAIL: TestUsernsCheckpoint (0.67s)
```

**Comment by kolyshkin** [comment]
I was wrong earlier. Since https://github.com/checkpoint-restore/criu/issues/2642 is closed (2 days ago), we use the same criu version (4.1) on Ubuntu 24.04 (amd64) and Ubuntu 22.04 (arm64), and it has not failed in there (yet?).

We also run CI on Fedora 41 (which has criu 4.0) and AlmaLinux 9 (criu 3.19), those are not failing. If repositories are provided, I can try running criu 4.1 on these two (AL9 and F41).

**Comment by kolyshkin** [comment]
criu 4.1 on F41 is not failing like this, instead it's failing in another way (https://github.com/checkpoint-restore/criu/issues/2650). Meaning, this issue is _probably_ specific to older kernels.

**Comment by kolyshkin** [comment]
Upsteam bug report (which is not about criu 4.1, as I filed in in Dec 2024): https://github.com/checkpoint-restore/criu/issues/2551

**Comment by kolyshkin** [comment]
This should be now fixed in criu v4.2, which we still don't have in https://copr.fedorainfracloud.org/coprs/adrian/criu-el8/ but I hope it's about to change thanks to @adrianreber.

**Comment by adrianreber** [comment]
Should be ready at https://copr.fedorainfracloud.org/coprs/adrian/criu-el8/build/9880138/

Once it is fixed in runc please close it here.

**Comment by kolyshkin** [comment]
This is now fixed with in CI thanks to @adrianreber change above (and earlier commit b520f750e):

>  criu x86_64 4.2-11.el8    copr:copr.fedorainfracloud.org:adrian:criu-el8 585 k

Hooray!

**Comment by HeRaNO** [comment]
It seems the new CRIU is not built with `libnftables`? And the `almalinux-8` action still fails.

The relevant log (from https://cirrus-ci.com/task/5192923664351232) is:

```text
=== RUN   TestUsernsCheckpoint
time="2025-12-09T04:43:18Z" level=warning msg="--- Quoting \"/tmp/TestUsernsCheckpoint2249346343/003/criu/dump.log\""
time="2025-12-09T04:43:18Z" level=warning msg="120:(00.108239) Will take user namespace in the image"
time="2025-12-09T04:43:18Z" level=warning msg="121:(00.108241) Add user ns 14 pid 51368"
time="2025-12-09T04:43:18Z" level=warning msg="122:(00.108249) net: Lock network"
time="2025-12-09T04:43:18Z" level=warning msg="123:(00.108251) Running network-lock scripts"
time="2025-12-09T04:43:18Z" level=warning msg="124:(00.108254) \tRPC"
time="2025-12-09T04:43:18Z" level=warning msg="125:(00.108534) Error (criu/net.c:3311): net: CRIU was built without libnftables support"
time="2025-12-09T04:43:18Z" level=warning msg="126:(00.108551) net: Unlock network"
time="2025-12-09T04:43:18Z" level=warning msg="127:(00.108554) Running network-unlock scripts"
time="2025-12-09T04:43:18Z" level=warning msg="128:(00.108556) \tRPC"
time="2025-12-09T04:43:18Z" level=warning msg="129:(00.108695) Error (criu/net.c:3389): net: CRIU was built without libnftables support"
time="2025-12-09T04:43:18Z" level=warning msg="130:(00.108701) Unfreezing tasks into 1"
time="2025-12-09T04:43:18Z" level=warning msg="131:(00.108703) \tUnseizing 51368 into 1"
time="2025-12-09T04:43:18Z" level=warning msg="132:(00.108715) Error (criu/cr-dump.c:2128): Dumping FAILED."
time="2025-12-09T04:43:18Z" level=warning msg=---
    checkpoint_test.go:113: criu failed: type DUMP errno 0
--- FAIL: TestUsernsCheckpoint (0.57s)
=== RUN   TestCheckpoint
time="2025-12-09T04:43:18Z" level=warning msg="--- Quoting \"/tmp/TestCheckpoint1455839718/003/criu/dump.log\""
time="2025-12-09T04:43:18Z" level=warning msg="118:(00.110156) Will take mnt namespace in the image"
time="2025-12-09T04:43:18Z" level=warning msg="119:(00.110158) Add mnt ns 13 pid 51723"
time="2025-12-09T04:43:18Z" level=warning msg="120:(00.110172) net: Lock network"
time="2025-12-09T04:43:18Z" level=warning msg="121:(00.110174) Running network-lock scripts"
time="2025-12-09T04:43:18Z" level=warning msg="122:(00.110176) \tRPC"
time="2025-12-09T04:43:18Z" level=warning msg="123:(00.111907) Error (criu/net.c:3311): net: CRIU was built without libnftables support"
time="2025-12-09T04:43:18Z" level=warning msg="124:(00.111945) net: Unlock network"
time="2025-12-09T04:43:18Z" level=warning msg="125:(00.111950) Running network-unlock scripts"
time="2025-12-09T04:43:18Z" level=warning msg="126:(00.111952) \tRPC"
time="2025-12-09T04:43:18Z" level=warning msg="127:(00.112040) Error (criu/net.c:3389): net: CRIU was built without libnftables support"
time="2025-12-09T04:43:18Z" level=warning msg="128:(00.112046) Unfreezing tasks into 1"
time="2025-12-09T04:43:18Z" level=warning msg="129:(00.112048) \tUnseizing 51723 into 1"
time="2025-12-09T04:43:18Z" level=warning msg="130:(00.112061) Error (criu/cr-dump.c:2128): Dumping FAILED."
time="2025-12-09T04:43:18Z" level=warning msg=---
    checkpoint_test.go:113: criu failed: type DUMP errno 0
--- FAIL: TestCheckpoint (0.43s)
```

**Comment by adrianreber** [comment]
I just changed the built to use the non nftables locking on EL8. The package was based on the Fedora package and there we use nftables based locking, but not on EL8. Please try once more.
