### ISSUE TITLE
Enable seccomp for s390x and ppc

### ISSUE THREAD

**Issue by michael-holzheu** [opencontainers/runc#866]
To enable seccomp for s390x and ppc we need to do the steps described in Docker issue docker/docker#23171.

For runc we have to:

 - Add runc patch #864 [already merged]
 - Bump versions in Godeps directory that include:

   * libseccomp-golang [1] : seccomp/libseccomp-golang@32f571b
   * runtime-spec [2] : opencontainers/runtime-spec#475 [merged -> d6fbe044c3ceace207b590339fb2fe039a761d42]

Ping @cyphar (since you did PR #842)
Ping @justincormack

**Comment by crosbymichael** [comment]
@michael-holzheu is this fully resolved now? I think we have everything merged..

**Comment by justincormack** [comment]
@crosbymichael no there is one commit missing from `libseccomp-golang` from here, `32f571b`

**Comment by michael-holzheu** [comment]
> @michael-holzheu is this fully resolved now? I think we have everything merged..

As @justincormack already noticed, the following commit is still missing: seccomp/libseccomp-golang@32f571b
